### ISSUE TITLE
usage with workspaces/monorepo - option for path to package.json

### ISSUE THREAD

**Issue by llaenowyd** [manovotny/github-releases-for-automated-package-publishing-action#13]
In a monorepo with yarn workspaces, [at the root there is a `package.json`](https://github.com/llaenowyd/cushman/blob/main/package.json) but it has some scripting and dev dependencies for maintenance, then there is a library package as [a workspace (subdirectory) that has its `package.json`](https://github.com/llaenowyd/cushman/blob/main/packages/lib/rito/package.json) - this one corresponding to the unit of release, so looking for e.g.

```yml
            - name: Validate and extract release information
              id: release
              uses: manovotny/github-releases-for-automated-package-publishing-action@v1.0.0
              with:
                  package-path: packages/lib/rito
```

Also but off topic, I could push a release tag for this unit of release, then the github action starts with

```yml
on:
  push:
    tags:
      - rito_v**
```

While this plugin doc shows a workflow starting with creating a Github release,

```yml
on:
    release:
        types: [created]
```

I haven't seen an example where this style is differentiated as the tag match above is.
